In [1]:
from IPython.core.display import display, HTML

import numpy as np
means = np.load("data/means.npy").astype(np.float32)
covs = np.load("data/covs.npy").astype(np.float32)
xicovs = np.load("data/xicovs.npy").astype(np.float32)
signals = np.load("data/signals.npy").astype(np.float32)
A = np.load("data/A.npy").astype(np.float32)
dt = np.load("data/dt.npy")[0]
C = np.load("data/C.npy").astype(np.float32)
D = np.load("data/D.npy").astype(np.float32)

In [27]:

from scipy.stats import norm
import matplotlib.pyplot as plt
from tqdm import tqdm
from misc import *
from RNN import *
import tensorflow as tf
%load_ext autoreload
%autoreload 2



The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [33]:
rec_layer = tf.keras.layers.RNN([MinimalRNNCell(2)], stateful=True, return_sequences=True)

In [34]:
rec_layer(tf.random.uniform((1,20,2)))

<tf.Tensor: shape=(1, 20, 2), dtype=float32, numpy=
array([[[-0.00220745,  0.00241735],
        [ 0.00378933, -0.00082914],
        [-0.00502508,  0.00596653],
        [-0.00362976,  0.00457912],
        [-0.00235881,  0.00326951],
        [-0.00355154,  0.00410452],
        [-0.00112109,  0.00410986],
        [-0.00923121,  0.00924448],
        [ 0.00584611, -0.00185574],
        [-0.00168401,  0.00172367],
        [-0.01082525,  0.00910991],
        [-0.00826666,  0.00793699],
        [-0.01128412,  0.00864519],
        [-0.0029081 ,  0.00503895],
        [-0.01596618,  0.01336796],
        [-0.01571734,  0.01269136],
        [-0.01652416,  0.01270723],
        [-0.01187695,  0.01104665],
        [ 0.00262432, -0.0004779 ],
        [-0.00973699,  0.00718729]]], dtype=float32)>

In [30]:
rec_layer.trainable_variables

[<tf.Variable 'rnn_6/stacked_rnn_cells/minimal_rnn_cell_6/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[ 0.03123149, -0.04009056],
        [-0.00789871, -0.04851898]], dtype=float32)>,
 <tf.Variable 'rnn_6/stacked_rnn_cells/minimal_rnn_cell_6/recurrent_kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[-0.00188458, -0.0253111 ],
        [ 0.01047443,  0.00777745]], dtype=float32)>]

In [22]:
rec_layer

In [24]:
rec_layer.trainable_variables

[<tf.Variable 'rnn_5/minimal_rnn_cell_5/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[-0.00971331,  0.04170433],
        [-0.02159089,  0.0262006 ]], dtype=float32)>,
 <tf.Variable 'rnn_5/minimal_rnn_cell_5/recurrent_kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[-0.00431148, -0.03923997],
        [-0.04932798, -0.02419574]], dtype=float32)>]