In [8]:
from IPython.core.display import display, HTML

import numpy as np
means = np.load("data/means.npy").astype(np.float32)
covs = np.load("data/covs.npy").astype(np.float32)
xicovs = np.load("data/xicovs.npy").astype(np.float32)
signals = np.load("data/signals.npy").astype(np.float32)
A = np.load("data/A.npy").astype(np.float32)
dt = np.load("data/dt.npy")[0]
C = np.load("data/C.npy").astype(np.float32)
D = np.load("data/D.npy").astype(np.float32)

In [28]:

from scipy.stats import norm
import matplotlib.pyplot as plt
from tqdm import tqdm
from misc import *
from RNN import *
import tensorflow as tf
%load_ext autoreload
%autoreload 2

tfsignals = tf.convert_to_tensor(signals)
tfxicovs = tf.convert_to_tensor(xicovs)[:-1]

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [29]:
coeffs = [C,A,D,dt]

In [30]:
model = RecModel(coeffs)

In [12]:


toysignals = tfsignals[:10][tf.newaxis,:,:]
toyxicovs = tfxicovs[:10][tf.newaxis,:,:,:]

In [15]:
inputs = (toyxicovs, toysignals)


In [33]:
tfsignals

<tf.Tensor: shape=(40000, 2), dtype=float32, numpy=
array([[-0.01571522, -0.00512357],
       [ 0.01813254, -0.02771763],
       [ 0.0548196 ,  0.02468396],
       ...,
       [ 0.04221111,  0.0035826 ],
       [ 0.04017262, -0.01458438],
       [-0.04898356, -0.01565416]], dtype=float32)>

In [31]:
model(inputs)

<tf.Tensor: shape=(1, 10, 2), dtype=float32, numpy=
array([[[-0.01571522, -0.00512357],
        [ 0.00244314, -0.03283308],
        [ 0.05725918, -0.00809588],
        [ 0.0586103 , -0.00044626],
        [ 0.01766581, -0.0501861 ],
        [ 0.05185269,  0.00608524],
        [ 0.04707159, -0.01011931],
        [ 0.02989107, -0.00090317],
        [ 0.03511429,  0.01495202],
        [ 0.05012804,  0.04540104]]], dtype=float32)>

In [32]:
means

array([[ 1.        ,  0.        ],
       [ 0.96982706, -0.00938743],
       [ 1.0011649 , -0.05978817],
       ...,
       [-9.186868  , -7.5970454 ],
       [-9.101876  , -7.5992446 ],
       [-9.184132  , -7.623677  ]], dtype=float32)