In [99]:
from IPython.core.display import display, HTML

import numpy as np
means = np.load("data/means.npy").astype(np.float32)
covs = np.load("data/covs.npy").astype(np.float32)
xicovs = np.load("data/xicovs.npy").astype(np.float32)
signals = np.load("data/signals.npy").astype(np.float32)
A = np.load("data/A.npy").astype(np.float32)
dt = np.load("data/dt.npy")[0]
C = np.load("data/C.npy").astype(np.float32)
D = np.load("data/D.npy").astype(np.float32)

In [176]:

from scipy.stats import norm
import matplotlib.pyplot as plt
from tqdm import tqdm
from misc import *
from RNN import *
import tensorflow as tf
%load_ext autoreload
%autoreload 2



The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [177]:
tfsignals = tf.convert_to_tensor(signals)
tfcovs = tf.convert_to_tensor(xicovs)[:-1]

In [178]:
rec_layer = tf.keras.layers.RNN([MinimalRNNCell(2,  coeffs=[C,A,D,dt])], stateful=True, return_sequences=True)

In [194]:
toysignals = tfsignals[:10]
toyxicovs = tfcovs[:10]

In [195]:
rec_layer((tf.expand_dims(toyxicovs, axis=0), tf.expand_dims(toysignals, axis=0)))

<tf.Tensor: shape=(1, 10, 2), dtype=float32, numpy=
array([[[-0.01571522, -0.00512357],
        [ 0.00244258, -0.03283247],
        [ 0.05725784, -0.00809445],
        [ 0.05861032, -0.00044631],
        [ 0.01766742, -0.05018786],
        [ 0.05185348,  0.00608433],
        [ 0.04707396, -0.01012191],
        [ 0.02989446, -0.00090688],
        [ 0.03511847,  0.01494746],
        [ 0.05013356,  0.04539504]]], dtype=float32)>

In [188]:
rec_layer()

InvalidArgumentError: Shapes of all inputs must match: values[0].shape = [1,10,2,2] != values[1].shape = [1,10,2] [Op:Pack] name: packed

In [147]:
tf.keras.layers.concatenate([toysignals[:,:,tf.newaxis], toyxicovs])

<tf.Tensor: shape=(10, 2, 3), dtype=float32, numpy=
array([[[-1.5715221e-02,  1.8165902e+00,  0.0000000e+00],
        [-5.1235720e-03,  0.0000000e+00,  1.8165902e+00]],

       [[ 1.8132543e-02,  1.8165902e+00,  7.6296792e-04],
        [-2.7717629e-02,  7.6296792e-04,  1.8165902e+00]],

       [[ 5.4819595e-02,  1.8165910e+00,  1.5234564e-03],
        [ 2.4683960e-02,  1.5234564e-03,  1.8165901e+00]],

       [[ 1.4448395e-03,  1.8165925e+00,  2.2814735e-03],
        [ 7.6359147e-03,  2.2814735e-03,  1.8165898e+00]],

       [[-4.0848449e-02,  1.8165947e+00,  3.0370271e-03],
        [-4.9741108e-02,  3.0370271e-03,  1.8165895e+00]],

       [[ 3.4215044e-02,  1.8165978e+00,  3.7901250e-03],
        [ 5.6189843e-02,  3.7901250e-03,  1.8165890e+00]],

       [[-4.6960181e-03,  1.8166015e+00,  4.5407754e-03],
        [-1.6195102e-02,  4.5407754e-03,  1.8165884e+00]],

       [[-1.7103555e-02,  1.8166060e+00,  5.2889856e-03],
        [ 9.1993930e-03,  5.2889856e-03,  1.8165877e+00]],

    

In [139]:
rec_layer([toysignals, toyxicovs])

ValueError: Shape (2, 10) must have rank at least 3

In [30]:
rec_layer.trainable_variables

[<tf.Variable 'rnn_6/stacked_rnn_cells/minimal_rnn_cell_6/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[ 0.03123149, -0.04009056],
        [-0.00789871, -0.04851898]], dtype=float32)>,
 <tf.Variable 'rnn_6/stacked_rnn_cells/minimal_rnn_cell_6/recurrent_kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[-0.00188458, -0.0253111 ],
        [ 0.01047443,  0.00777745]], dtype=float32)>]

In [22]:
rec_layer

In [24]:
rec_layer.trainable_variables

[<tf.Variable 'rnn_5/minimal_rnn_cell_5/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[-0.00971331,  0.04170433],
        [-0.02159089,  0.0262006 ]], dtype=float32)>,
 <tf.Variable 'rnn_5/minimal_rnn_cell_5/recurrent_kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[-0.00431148, -0.03923997],
        [-0.04932798, -0.02419574]], dtype=float32)>]